name: echo
description: A starting point for Dart libraries or applications.
version: 0.0.3
# homepage: https://www.example.com

environment:
  sdk: ">=2.20.0 <3.0.0"

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  shelf_router: ^1.1.4
  path: ^1.8.3
  lints: ^2.1.1
  shelf: ^1.4.1

dev_dependencies:
  test: ^1.24.4
